"""Stage a reduced Windows runtime without changing the original installation."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import struct
import re
import csv
import io
import base64

ROOT = Path(__file__).resolve().parents[1]
QT = Path('Lib/site-packages/PySide6')
DEV_PACKAGES = {'pip', 'setuptools', 'wheel', '_distutils_hack'}
MS_RUNTIME = re.compile(r'^(?:msvcp140(?:_\w+)?|vcruntime140(?:_\w+)?|concrt140|vcomp140|vcamp140|vccorlib140|mfc140\w*|mfcm140\w*)\.dll$', re.I)


def write_upgrade_cleanup(destination, report):
    lines = ['; Generated by work/build_runtime.py. Only known obsolete runtime files.', '[InstallDelete]']
    for row in report['files']:
        if row['excluded']:
            relative = Path(row['path'])
            if relative.is_absolute() or '..' in relative.parts or '"' in row['path']:
                raise ValueError('Unsafe cleanup path')
            name = row['path'].replace('/', '\\')
            lines.append('Type: files; Name: "{app}\\runtime\\' + name + '"')
    destination.with_name(destination.name + '.cleanup.iss').write_text('\n'.join(lines) + '\n', encoding='utf-8')


def verify(destination):
    destination = destination.resolve()
    report = json.loads((destination / 'runtime-manifest.json').read_text(encoding='utf-8'))
    expected = {r['path']: r for r in report['files'] if not r['excluded']}
    actual = {p.relative_to(destination).as_posix() for p in destination.rglob('*')
              if p.is_file() and p.name != 'runtime-manifest.json'}
    if set(expected) != actual:
        raise RuntimeError(f'Runtime manifest mismatch: extra={actual - set(expected)}, missing={set(expected) - actual}')
    for relative, row in expected.items():
        if hashlib.sha256((destination / relative).read_bytes()).hexdigest() != row['sha256']:
            raise RuntimeError(f'Runtime file changed: {relative}')
    write_upgrade_cleanup(destination, report)
    print(f'Verified {len(expected)} runtime files; generated exact-file upgrade cleanup')


def pe_imports(path):
    """Read normal and delay-load imports; no DLL execution required."""
    data = path.read_bytes()
    pe = struct.unpack_from('<I', data, 0x3c)[0]
    if data[pe:pe + 4] != b'PE\0\0':
        raise ValueError(f'Not a PE binary: {path}')
    sections, opt_size = struct.unpack_from('<H12xH', data, pe + 6)
    opt = pe + 24
    magic = struct.unpack_from('<H', data, opt)[0]
    directories = opt + (112 if magic == 0x20b else 96)
    table = opt + opt_size
    mappings = []
    for i in range(sections):
        virtual_size, rva, raw_size, raw = struct.unpack_from('<IIII', data, table + i * 40 + 8)
        mappings.append((rva, max(virtual_size, raw_size), raw))

    def offset(rva):
        for start, size, raw in mappings:
            if start <= rva < start + size:
                return raw + rva - start
        if rva < table:
            return rva
        raise ValueError(f'Unmapped RVA {rva} in {path}')

    names = set()
    for index, stride, name_field in ((1, 20, 12), (13, 32, 4)):
        rva, size = struct.unpack_from('<II', data, directories + index * 8)
        if not rva:
            continue
        cursor = offset(rva)
        while any(data[cursor:cursor + stride]):
            name_rva = struct.unpack_from('<I', data, cursor + name_field)[0]
            if name_rva:
                start = offset(name_rva)
                names.add(data[start:data.index(b'\0', start)].decode('ascii').lower())
            cursor += stride
    return names


def qt_files(source):
    qt = source / QT
    required = {'__init__.py', '_config.py', '_git_pyside_version.py',
                'QtCore.pyd', 'QtGui.pyd', 'QtWidgets.pyd',
                'plugins/platforms/qwindows.dll', 'plugins/platforms/qoffscreen.dll',
                'plugins/styles/qmodernwindowsstyle.dll', 'plugins/imageformats/qico.dll'}
    # Resolve Qt's own native dependencies rather than guessing a DLL list.
    local_dlls = {p.name.lower(): p for p in qt.glob('*.dll')}
    pending = [qt / p for p in required if p.endswith(('.dll', '.pyd'))]
    visited = set()
    while pending:
        path = pending.pop()
        if path in visited:
            continue
        visited.add(path)
        for dependency in pe_imports(path):
            if dependency in local_dlls:
                dll = local_dlls[dependency]
                required.add(dll.relative_to(qt).as_posix())
                pending.append(dll)
    # Binding support is Python code, used lazily by signatures and features.
    required.update(p.relative_to(qt).as_posix() for p in (qt / 'support').rglob('*')
                    if p.is_file() and '__pycache__' not in p.parts)
    return required


def exclusion(relative, qt_keep):
    parts = relative.parts
    if MS_RUNTIME.match(relative.name):
        return 'Microsoft runtime installed directly from Microsoft, not redistributed in this package'
    if '__pycache__' in parts or relative.suffix in {'.pyc', '.pyo'}:
        return 'Python bytecode cache'
    if parts[0].lower() == 'scripts':
        return 'Developer command-line launchers'
    if relative.is_relative_to(QT):
        return None if relative.relative_to(QT).as_posix() in qt_keep else 'Unused Qt module, plugin, multimedia or SDK tool'
    if relative.is_relative_to(Path('Lib/site-packages')):
        name = parts[2]
        if name == 'bin':
            return 'Developer command-line launchers generated by pip --target'
        if relative.name == 'direct_url.json':
            return 'Build-local wheel cache URL; public origin is in bootstrap-lock.json'
        if name in {'av', 'av.libs'} or name.startswith('av-'):
            return 'File codecs are not used by Dictatoro PCM-only recognition'
        if relative.name.lower().startswith('cudnn') and relative.suffix.lower() == '.dll':
            return 'Unused NVIDIA GPU runtime: Dictatoro uses CPU inference'
        if name.lower().startswith(('pyside6_addons-', 'pyside6-')):
            return 'Unused PySide6 Addons / umbrella metadata'
        if name in DEV_PACKAGES or any(name.startswith(p + '-') for p in DEV_PACKAGES):
            return 'Python packaging tool'
        if name in {'distutils-precedence.pth', 'easy_install.py'}:
            return 'Python packaging bootstrap'
        if relative.name.lower().endswith('-asio.dll'):
            return 'Optional unused ASIO driver'
    return None


def apply_runtime_patch(relative, target):
    if relative.as_posix() == 'Lib/site-packages/faster_whisper/audio.py':
        original = target.read_text('utf-8')
        assert original.count('import av\n') == 1, 'Review upstream audio.py before patching'
        updated = original.replace('import av\n', '''# Dictatoro patch 2026-09-12: PyAV is optional for ndarray microphone input.
try:
    import av
except ModuleNotFoundError as exc:
    if exc.name != "av":
        raise
    av = None
''')
        marker = '    resampler = av.audio.resampler.AudioResampler('
        assert updated.count(marker) == 1
        updated = updated.replace(marker, '''    if av is None:
        raise RuntimeError("This Dictatoro build accepts PCM arrays; file decoding is not included.")
''' + marker)
        target.write_text(updated, encoding='utf-8')
        return 'faster-whisper 1.2.1: optional PyAV, explicit unsupported file-input error'
    if relative.as_posix() == 'Lib/site-packages/faster_whisper-1.2.1.dist-info/METADATA':
        text = target.read_text('utf-8')
        assert 'Requires-Dist: av>=11\n' in text
        target.write_text(text.replace('Requires-Dist: av>=11\n', '') +
                         '\nDictatoro distribution patch: PCM-only use; optional PyAV is not bundled.\n', encoding='utf-8')
        return 'Remove unused mandatory PyAV dependency in patched distribution metadata'
    return None


def build(source, destination):
    source = source.resolve()
    destination = destination.resolve()
    if not destination.is_relative_to(ROOT.parent) or destination == source or source.is_relative_to(destination):
        raise ValueError('Destination must be a new directory within the source parent directory')
    if destination.exists():
        raise FileExistsError(f'Refusing to mix old and new files: {destination}')
    qt_keep = qt_files(source)
    unexpected = {p for p in qt_keep if p.startswith('Qt6') and p not in {'Qt6Core.dll', 'Qt6Gui.dll', 'Qt6Widgets.dll'}}
    if unexpected:
        raise RuntimeError(f'Review additional Qt dependencies before packaging: {unexpected}')
    destination.mkdir(parents=True)
    records = []
    original_bytes = 0
    for path in sorted(source.rglob('*')):
        if not path.is_file():
            continue
        relative = path.relative_to(source)
        reason = exclusion(relative, qt_keep)
        row = {'path': relative.as_posix(), 'bytes': path.stat().st_size, 'excluded': reason}
        original_bytes += row['bytes']
        if not reason:
            target = destination / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, target)
            row['modification'] = apply_runtime_patch(relative, target)
            row['original_sha256'] = hashlib.sha256(path.read_bytes()).hexdigest()
            row['sha256'] = hashlib.sha256(target.read_bytes()).hexdigest()
            row['bytes'] = target.stat().st_size
        records.append(row)
    # Normalize wheel records to the files actually shipped. This removes cache URLs,
    # references to stripped developer tools and path-dependent pip launcher hashes.
    # Keep RECORD itself unhashed, as in the wheel format.
    for row in records:
        relative = Path(row['path'])
        if row['excluded'] or relative.name != 'RECORD' or not relative.parent.name.endswith('.dist-info'):
            continue
        record = destination / relative
        normalized = []
        for name, old_hash, old_size in csv.reader(io.StringIO(record.read_text('utf-8'))):
            item = (record.parent.parent / name).resolve()
            if not item.is_relative_to(destination) or not item.is_file():
                continue
            if item == record:
                normalized.append([name, '', ''])
            else:
                data = item.read_bytes()
                digest = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b'=').decode()
                normalized.append([name, 'sha256=' + digest, str(len(data))])
        buffer = io.StringIO(newline='')
        csv.writer(buffer, lineterminator='\n').writerows(sorted(normalized))
        record.write_text(buffer.getvalue(), encoding='utf-8', newline='\n')
        row['sha256'] = hashlib.sha256(record.read_bytes()).hexdigest()
        row['bytes'] = record.stat().st_size
        row['modification'] = 'Normalize RECORD for the retained distribution; remove build-local entries'
    report = {'source': str(source), 'destination': str(destination),
              'original_bytes': original_bytes,
              'retained_bytes': sum(r['bytes'] for r in records if not r['excluded']),
              'qt_files': sorted(qt_keep), 'files': records,
              'unresolved_licensing': ['Intel MKL static redistribution conditions and third-party notices',
                                       'Intel OpenMP redistribution conditions',
                                       'Final corresponding-source/build provenance review']}
    (destination / 'runtime-manifest.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
    write_upgrade_cleanup(destination, report)
    print(json.dumps({k: report[k] for k in ('original_bytes', 'retained_bytes', 'qt_files')}, indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--source', type=Path, default=ROOT.parent / 'runtime-input')
    parser.add_argument('--destination', type=Path, default=ROOT.parent / 'Dictatoro-0.3-runtime-qt6112-final')
    parser.add_argument('--verify', action='store_true')
    args = parser.parse_args()
    if args.verify:
        verify(args.destination)
    else:
        build(args.source, args.destination)
